web:
  container_name: jira-mg-develop.hipay-pos-platform.com
  build: .
  dockerfile: ./bin/docker/php5-6/Dockerfile
  ports:
      - "80:80"
  env_file:
    - ./bin/conf/production/hipay.env
mysql:
  image: mysql:5.6.23
  env_file:
     - ./bin/conf/production/hipay.env
smtp:
  container_name: smtp-hipay-mg-develop
