web:
  container_name: {CONTAINER_NAME_WEB}
  build: .
  dockerfile: ./bin/docker/php5-6/Dockerfile
  ports:
      - "{PORT_WEB}:80"
  env_file:
    - ./bin/conf/production/hipay.env
mysql:
  image: mysql:5.6.23
  ports:
    - "{PORT_MYSQL}:3306"
  env_file:
     - ./bin/conf/production/hipay.env
smtp:
  container_name: {CONTAINER_NAME_SMTP}
